### ISSUE TITLE
About the running

### ISSUE THREAD

**Issue by Koenigsegg-One1** [malllabiisc/kg-geometry#2]
Is there any order of execution? I am running typeAnalysis.py firstly, however, I get an error that I don't have the file "ent.fb15k.p". Looking forward to your reply, Thanks.

**Comment by Chandrahasd** [comment]
Hi @Koenigsegg-One1 

Thank you for your interest in our work.
Please follow the following execution order:
```
python typeAnalysis.py -m <data-directory> -d <dataset-name> -g <conicity/length> --opdir <output-directory> --type <ent/rel>
python typeAnalysis.py -m <data-directory> -d <dataset-name> -g <conicity/length> --opdir <output-directory> --type <ent/rel> --result #(for generating the plots)
```

Please note that the first command generates the necessary file (`ent.fb15k.p`) while the second one (with the `--result `option) uses that file. Let me know if it resolves the issue.
