### ISSUE TITLE
Same Experiment on FB15K-237

### ISSUE THREAD

**Issue by Walker-ZD** [malllabiisc/kg-geometry#3]
&emsp;Thanks for your work. I did the same experiment on FB15K-237, but I can only get the summary 6.1 and summary 6.3.  
&emsp;I wonder whether there is any explanation of summary 6.1 and 6.3. Why such a pattern?
&emsp;Looking forward to your reply.

**Comment by Chandrahasd** [comment]
@StrugglerDream, thank you for your interest in our work.

Summary 6.1 highlights the basic difference in the scoring functions. Multiplicative scores depend upon the inner product, which is usually maximized by bringing the vectors closer in terms of angle, assuming fixed dimensional vectors.

However, with a higher number of dimensions, the model is more flexible to maximize inner products by increasing vector lengths. Therefore, we see the pattern in Summary 6.3.

I hope this answers your question.

**Comment by Walker-ZD** [comment]
&emsp;OK, I understand, thank you.
